version: 2
jobs:
  build-container:
    docker:
      - image: docker:git

    working_directory: ~/container

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker build -t lifely/mongo-restore-container:$CIRCLE_SHA1 .

  push-to-docker:
    docker:
      - image: docker:git

    working_directory: ~/container

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker build -t lifely/mongo-restore-container:latest -t lifely/mongo-restore-container:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push lifely/mongo-restore-container:$CIRCLE_SHA1
          docker push lifely/mongo-restore-container:latest

workflows:
  version: 2
  build:
    jobs:
      - build-container:
          filters:
            branches:
              ignore: master
      - push-to-docker:
          context: docker-hub-auth
          filters:
            branches:
              only: master
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
                 - develop
     jobs:
       - build-container
